Add support for building OCaml variant versions
ocurrent/ocaml-ci pull request #241
Opened 2020-08-11 11:26 UTC by avsm

This adds support for parsing compiler variants (e.g. flambda) in
the Variant module.

The arch value is now explicitly specified, so the build modules can
choose whether to introduce a personality or not in their
Dockerfiles.

The configuration now uses Ocaml_version to setup the various
architecture choices.  This just adds flambda to the set of
tested defaults, using the latest stable compiler version.

2020-08-11 11:26 UTC, avsm commented
This is the "good bits" of #236 to support compiler variants like flambda

2020-08-11 11:32 UTC, avsm commented
I'll test this on live later on this afternoon. It shouldn't change much externally except flambda being added to the test matrix.

2020-08-25 07:29 UTC, avsm commented
Pushing this live as a test

2020-09-03 09:58 UTC, talex5 approved these changes

2020-09-03 16:11 UTC, avsm commented
I'll push this live again now.

2020-09-04 07:51 UTC, talex5 requested changes
This PR reverted some changes in OCurrent. That should be fixed.

2020-09-04 11:16 UTC, avsm commented
It should be on ocurrent master now I think

2020-09-04 11:28 UTC, talex5 commented
Ah, I see the problem: https://github.com/ocurrent/ocurrent/pull/219 hadn't been merged, so updating to master reverted that.

2020-09-04 11:54 UTC, avsm commented
Ok merged it in and also cherry-picked d787bd0176409044dc2e29bbb8519224fcfb8c3e from #245 so the history is clean now

2020-09-04 11:59 UTC, avsm commented
Pushed this branch to live-engine

2020-09-04 12:20 UTC, talex5 approved these changes

2020-09-04 12:21 UTC, merged