Opam monorepo 0 2
ocurrent/ocaml-ci pull request #288
Opened 2020-12-16 16:15 UTC by emillon

This adds support to the 0.2 lock file format. It is identical to the 0.1 one, with the extra guarantee that `depexts` in the lock file contain all the transitive dependencies. This removes the need to pin recursively (and to access opam-repository).

Closes #282

2020-12-16 16:16 UTC, emillon commented
Keeping this WIP until the corresponding plugin is released.

2020-12-22 14:25 UTC, emillon commented
This one is now ready. It actually does not need a plugin release so can be merged when convenient.

2020-12-22 18:39 UTC, talex5 requested changes
I tried this on realworldocaml and it generated an empty `RUN` line:
```
RUN sudo chown opam /src
RUN cd ~/opam-repository && (git cat-file -e 51576718e3d32386fcc2248de168f74e990b4a42 || git fetch origin master) && git reset -q --hard 51576718e3d32386fcc2248de168f74e990b4a42 && git log --no-decorate -n1 --oneline && opam update -u
RUN 
```
I guess it's from `pin_opam_files`.

2020-12-23 09:34 UTC, emillon commented
I just fixed it. This used to fail because it would generate `mkdir -p` (and no directories), so I filtered in `mkdir`, but it's cleaner to filter in `pin_opam_files` to avoid the empty `RUN` indeed.

If you want to try it on a 0.2 build, there's a branch `format-0-2` on realworldocaml/book (which builds fine locally).

2020-12-23 09:43 UTC, merged

2020-12-23 10:11 UTC, talex5 commented
I don't see a [format-0-2](https://github.com/realworldocaml/book/tree/format-0-2) branch, but it seems happy on `master` so merged!

2020-12-23 10:20 UTC, emillon commented
Ah, I forgot to push it indeed. I cherry picked it on an existing PR, and it worked: https://ci.ocamllabs.io/github/realworldocaml/book/commit/60b370cd69cb8fbcfedd22ecf45db1ed06acdb37/variant/debian-10-4.10