Mobile version: organisation
ocurrent/ocaml-ci pull request #662
Opened 2022-12-07 09:24 UTC by maiste

This is part of #656. It supersedes a part of #657.

It fixes an issue when it can't find the organisation page in the page chosen and implements a version for mobile of the organisation page.

2022-12-07 09:24 UTC, maiste commented
![organisation](https://user-images.githubusercontent.com/22150236/206139926-8d52c643-9c6b-492c-8ea8-ffa0bf8ce2cf.gif)

2022-12-07 11:33 UTC, benmandrew commented
On Safari mobile the text does not wrap correctly. For some reason the flex-col is not contained within the container, as can be seen in the image below. I tried messing around with the CSS but couldn't find a fix for it.

<img width="768" alt="Git forge URLs overflow outside of their containing item-cards" src="https://user-images.githubusercontent.com/13054139/206168258-d79910de-af3e-4f87-88c6-a7c95c2ef6f2.png">

This is not just for unrealistically small screen sizes: the problem persists for iPhone 8 and 8 Plus.

2022-12-07 11:37 UTC, benmandrew requested changes
Above

2022-12-08 01:13 UTC, novemberkilo approved these changes
Thanks @maiste - you can add CSS to your list of expertise now :)

2022-12-08 01:13 UTC, novemberkilo commented on web-ui/view/organisation.ml
> +    Logs.warn (fun l -> l "Image is %S" url);
Maybe drop the logs if you don't need them anymore?

2022-12-08 01:16 UTC, novemberkilo commented
Regarding the issue raised by @benmandrew - I suggest shipping this and opening an issue. I'm not sure we're going to be able to support a perfect experience for portrait mode on phones on all browsers. Let's collect the issues and see if there are any deal breakers?

2022-12-08 12:24 UTC, merged