CSS line numbers for logs
ocurrent/ocaml-ci pull request #723
Opened 2023-01-10 12:35 UTC by benmandrew

Fix for #654 using @novemberkilo's CSS suggestion.

Copying logs no longer pulls in line numbers (tested in Safari 15.2).

2023-01-10 13:23 UTC, benmandrew commented
Not yet ready for merging: multi-line log lines do not have line numbers or associated formatting beyond the first line (see image), and causes the logs background issue in #716 to return.

<img width="334" alt="Screenshot 2023-01-10 at 13 21 29" src="https://user-images.githubusercontent.com/13054139/211562946-90dedafe-7e8d-48ff-b292-e4254ed92d4a.png">

2023-01-10 13:46 UTC, maiste commented
Thanks for the PR :+1: 

I've tested _Copy/Paste_ for `Step to reproduce` and `Logs` on:
- Mozilla Firefox 108.0.1
- Chromium 108.0.5359.124

It seems to work fine (appart for the issue you where suggesting). The background problem can be solved in this configuration by adding `bg-default` to this [line](https://github.com/ocurrent/ocaml-ci/blob/108990a014bf7452c0cfbbc4a13becf5cdff3b92/web-ui/view/step.ml#L423).

2023-01-10 14:11 UTC, maiste reviewed
Now that we have the tailwind machinery setup in place, it's nice to use it to avoid having conflict between custom CSS and tailwind generated one (e.g. `whitespace` as an example). It's also capable of optimising some parts of the generated code, so we should use it as much as possible :)

2023-01-10 14:11 UTC, maiste commented on web-ui/static/css/style.css
>    @apply text-gray-900 dark:text-gray-100 bg-gray-200 dark:bg-gray-850 text-center px-1 md:px-6 w-14 text-gray-700 text-sm cursor-pointer select-none border-none;
```suggestion
  content: counter(linenum);
  @apply block text-gray-900 dark:text-gray-100 bg-gray-200 dark:bg-gray-850 text-center px-1 md:px-6 w-14 text-gray-700 text-sm text-right cursor-pointer select-none border-none;
```

2023-01-10 14:11 UTC, maiste commented on web-ui/static/css/style.css
> +  counter-increment: linenum;
```suggestion
  counter-increment: linenum;
    @apply table-row;
```

2023-01-10 14:11 UTC, maiste commented on web-ui/static/css/style.css
> +  border-left: 1px solid transparent;
```suggestion
  @apply table table-fixed w-full whitespace-pre-wrap border-l  border-solid border-transparent text-sm;
  font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", "Courier New", monospace;
```

2023-01-12 15:40 UTC, maiste commented on web-ui/view/step.ml
> +        | _ :: l -> last l
```suggestion
        | [ s ] -> s
        | _ :: l -> last l
```

2023-01-12 15:42 UTC, maiste commented on web-ui/view/step.ml
> +      |> List.map (fun l -> l |> collapse_carriage_returns |> Ansi.process ansi)
```suggestion
      |> List.map (fun l -> collapse_carriage_returns l |> Ansi.process ansi)
```

2023-01-13 11:46 UTC, maiste commented
git clone --recursive "https://github.com/maiste/ocaml-ci-experiment.git" -b "no-format" && cd "ocaml-ci-experiment" && git reset --hard a033e
cat > Dockerfile <<'END-OF-DOCKERFILE'
FROM ocaml/opam@sha:e4ce65485aed7b09b605f39643b46b86b913b54f5304e0dc125d815d18805887
# debian--4.14_opam-2.1
USER :1000
ENV CLICOLOR_FORCE=""
ENV OPAMCOLOR="always"
WORKDIR /src
RUN sudo ln -f /usr/bin/opam-.1 /usr/bin/opam
RUN opam init --reinit -ni
WORKDIR /src
RUN sudo chown opam /src
RUN cd ~/opam-repository && (git cat-file -e c64f99389df018a1aa5f82610c3fe74cc1cbbc8 || git fetch origin master) && git reset -q --hard 0c64f99389df018a1aa5f82610c3fe74cc1cbbc8 && git log --no-decorate -n1 --oneline && opam update -u
COPY --chown=:1000 test.opam ./
RUN opam pin add -yn test.dev './'
ENV DEPS="base-bigarray.base base-threads.base base-unix.base dune..6.1 ocaml.4.14.1 ocaml-base-compiler.4.14.1 ocaml-config.2 ocaml-options-vanilla.1"
ENV CI="true"
ENV OCAMLCI="true"
RUN opam update --depexts && opam install --cli=.1 --depext-only -y test.dev $DEPS
RUN opam install $DEPS
COPY --chown=:1000 . /src
RUN opam exec -- dune build @install @check @runtest && rm -rf _build

END-OF-DOCKERFILE
docker build .

2023-01-13 11:48 UTC, maiste requested changes
Only one change is required in the review here: `List.compare_length_with`. Otherwise, it can be merged on the master.

Working on Firefox.108.0.2 and Chromium.109.0.5414.74

2023-01-13 11:48 UTC, maiste commented on web-ui/view/step.ml
> +      (* let first_idx, last_idx = (0, List.length data - 1) in *)
This can be removed.

2023-01-13 11:48 UTC, maiste commented on web-ui/view/step.ml
> +          if List.length split > 1 then List.iter (Dream.log "%S") split;
```suggestion
          if (List.compare_length_with split 1) >= 1 then List.iter (Dream.log "%S") split;
```
`List.compare_length_with` stops the computation at 1 iteration. It avoids unecessary computation.

2023-01-13 11:48 UTC, maiste commented on web-ui/view/step.ml
> +        let data' = data |> process_logs in
```suggestion
        let data' = process_logs data in
```

2023-01-13 11:48 UTC, maiste commented on web-ui/view/step.ml
> +              let data' = data |> process_logs in
```suggestion
              let data' = process_logs data in
```

2023-01-13 12:17 UTC, merged