Refactor time in the CI
ocurrent/ocaml-ci pull request #771
Opened 2023-03-03 14:22 UTC by maiste

This PR is an attempt to reduce duplication with time modules. It is composed of several step, that's why it is still a draft:
- [X] Factorise in module `lib_client/run_time.ml`
- [ ] Factorise in module `lib/run_time.ml` (DOING @maiste)
- [ ]  See if we can merge the two modules.
- [ ] Simplify the code of `timestamp_duration`
- [ ] Add hints to make the data more comprehensible for the user.

2023-03-07 09:46 UTC, novemberkilo commented
@maiste I have been looking at #632 and did some of the analysis of where `web-ui/view/timestamps_durations` is used. It turns out that very little of it is actually used (and I suspect a lot of it is left over from the previous UI of ocaml-ci). I can build the project with everything deleted except for:

```
to_ts_string
pp_timestamp
pp_duration
```

Hope this helps.

2023-03-07 09:58 UTC, MisterDA commented
I suggest to rebase on top of master, or merge master back here.

2023-03-07 10:19 UTC, maiste commented
> been

Thanks, @novemberkilo! It will help me a lot to simplify the code :)

2023-03-07 11:03 UTC, MisterDA requested changes
Found a few places where I think the code could be reduced in size.

2023-03-07 11:03 UTC, MisterDA commented on lib_client/run_time.ml
> +    |> List.fold_left (fun subtotal rt -> subtotal +. TimeInfo.total rt) 0.
This could be combined without to have to walk the list three times, but perhaps it doesn't matter too much.

2023-03-07 11:03 UTC, MisterDA commented on lib_client/run_time.ml
> +      |> List.rev
```suggestion
      |> List.sort (fun x y -> Float.compare x y |> Int.neg)
```

2023-03-07 11:03 UTC, MisterDA commented on lib_client/run_time.ml
> +      Ok (List.fold_left minn max_float jil)
```suggestion
      let min acc (ji : Client.job_info) =
        Option.fold ~none:acc ~some:(fun v -> min acc v) ji.queued_at
      in
      Ok (List.fold_left min max_float jil)
```
is fine. Not a fan of `jil` for _job info list_ but that's ok.

2023-03-08 05:24 UTC, novemberkilo approved these changes
Thank you for this work @maiste - future developers of OCaml-CI will certainly appreciate this refactoring and consolidation :) 

Suggestion to please make sure we are no longer using "client" anywhere, including in filenames. For example, there are two tests in `test/service` - one is `test_run_time.ml` and the other is `test_run_time_client.ml`

2023-03-08 11:43 UTC, benmandrew approved these changes
Looks great to me, thanks so much for this!

2023-03-09 15:03 UTC, MisterDA approved these changes

2023-03-09 15:03 UTC, merged