Support exotic architectures removed in OCaml 5.0
ocurrent/ocaml-ci pull request #780
Opened 2023-03-08 10:15 UTC by benmandrew

Support for s390, arm32, x86_32, and ppc64 have not yet been added to OCaml 5.0, but we attempt to build these combinations anyway and fail, leaving the architectures untested. This PR uses a change in `ocaml-version` (https://github.com/ocurrent/ocaml-version/pull/61) to choose the latest version of OCaml that is supported by a given architecture.

This cannot be merged until the `ocaml-version` change is merged and released.

Fixes https://github.com/ocurrent/ocaml-ci/issues/756.

2023-03-12 23:57 UTC, tmcgilchrist commented
@benmandrew re-vendor `ocaml-version` and try this out on ocaml-ci against [https://github.com/mirage/mirage-crypto](https://github.com/mirage/mirage-crypto/)

2023-03-13 11:47 UTC, kit-ty-kate requested changes
OCaml-CI should instead test 4.14 and 5.0 as if they were both latest versions, given 4.14 is LTS. This is what opam-repo-ci does for example (see https://github.com/ocurrent/opam-repo-ci/pull/196)

2023-03-15 10:18 UTC, benmandrew commented
I've vendored ocaml-version pointing to my own fork.

Basic question, but if the changes are OCaml-CI specific then what's the standard way to integrate a submodule in? Pointing to my fork isn't a permanent solution, but it also seems strange to maintain a separate branch on [`ocurrent/ocaml-version`](https://github.com/ocurrent/ocaml-version) specifically for usage in OCaml-CI.

2023-03-15 11:50 UTC, kit-ty-kate commented on service/conf.ml
> +  OV.(List.map with_just_major_and_minor Releases.[ v4_14; v5_0 ])
```suggestion
  OV.(List.map with_just_major_and_minor Releases.[ v4_14; latest ])
```

2023-03-15 11:54 UTC, kit-ty-kate commented
I don't understand why this fork is necessary

2023-03-15 13:32 UTC, kit-ty-kate commented
> OCaml-CI assumes that all architectures work fully on 5.0+. It tries to build these architectures with the master distro and latest version, which fails at some point leading to those arches not being tested. 

They all do work though, only in bytecode-only mode (which is a valid state of the OCaml compiler).

The issue in https://github.com/ocurrent/ocaml-ci/issues/756 is just that when a package depends on `num` then it won't be tested due to `num` being unavailable in bytecode-only mode. So simply testing both 4.14 and 5.0 fixes this issue and the ocaml-version fork is not needed.

2023-03-15 14:27 UTC, benmandrew commented
Ahh I understand what you mean, thanks for the explanation.

2023-03-15 14:29 UTC, kit-ty-kate approved these changes

2023-03-15 15:57 UTC, merged